# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2df781582bb9bdc00622ab616e555adab1a77b2d97b1a5d1ce84601c2b48f8915a59c1807e0b41ff5736b86113be7518623ee90eea201cd529b64b5c7bd9110f

test:
  secret_key_base: 00f09c57de27643b0be84216863a971fdd9b2b0be2e205010ac596525a41bd3fdda5f5849c2077225ddc92dc966a2c85cfe753374adb328917ab7f5521d25548

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
